<?php
/**
 * GameSense Fantasy - Chicken Game
 * Pick eggs to reveal gems or bones. Cash out anytime!
 */

require_once '../config/config.php';

$page_title = "Chicken Game";
$page_description = "Pick eggs and avoid bones in this exciting risk-reward game!";
$page_css = "game.css";
$page_js = "chicken.js";

include '../includes/header.php';
?>

<div class="game-container">
    <div class="game-wrapper">
        <!-- Game Area -->
        <div class="game-area">
            <h2 class="game-title">🐔 CHICKEN GAME 🥚</h2>
            
            <div class="game-content">
                <!-- Egg Grid -->
                <div id="eggGrid" class="egg-grid">
                    <!-- Grid will be generated by JavaScript -->
                </div>
                
                <!-- Game Stats -->
                <div class="game-stats mt-lg">
                    <div class="stat-box">
                        <span class="stat-label">Current Multiplier:</span>
                        <span class="stat-value text-gold" id="currentMultiplier">1.00x</span>
                    </div>
                    <div class="stat-box">
                        <span class="stat-label">Eggs Revealed:</span>
                        <span class="stat-value text-gold" id="eggsRevealed">0/20</span>
                    </div>
                    <div class="stat-box">
                        <span class="stat-label">Potential Win:</span>
                        <span class="stat-value text-success" id="potentialWin">0</span>
                    </div>
                </div>
                
                <!-- How to Play -->
                <div class="game-instructions mt-lg p-md card">
                    <h3 class="text-gold mb-md">📖 How to Play</h3>
                    <ul>
                        <li>💰 Place your bet and click "START GAME"</li>
                        <li>🥚 Click eggs to reveal gems or bones</li>
                        <li>💎 Each gem increases your multiplier</li>
                        <li>🦴 Hit a bone = Game Over (lose bet)</li>
                        <li>💵 Click "CASH OUT" anytime to collect winnings</li>
                        <li>🎯 More eggs revealed = higher multiplier = bigger risk!</li>
                    </ul>
                </div>
            </div>
        </div>
        
        <!-- Control Panel -->
        <div class="control-panel">
            <h2 class="control-title">Game Controls</h2>
            
            <div class="control-section mb-xl">
                <label class="label-text">Bet Amount</label>
                <div class="input-group">
                    <input type="number" id="betAmount" value="10" min="1" max="500">
                    <span class="input-suffix">Coins</span>
                </div>
                <div class="quick-bet-buttons mt-md">
                    <button class="btn btn-sm btn-secondary quick-bet" data-amount="10">10</button>
                    <button class="btn btn-sm btn-secondary quick-bet" data-amount="50">50</button>
                    <button class="btn btn-sm btn-secondary quick-bet" data-amount="100">100</button>
                    <button class="btn btn-sm btn-secondary quick-bet" data-amount="max">MAX</button>
                </div>
            </div>
            
            <div class="control-section mb-xl">
                <label class="label-text">Number of Bones</label>
                <select id="boneCount" class="form-select">
                    <option value="3">3 Bones (Easy)</option>
                    <option value="5" selected>5 Bones (Medium)</option>
                    <option value="7">7 Bones (Hard)</option>
                </select>
            </div>
            
            <div class="control-section mb-xl">
                <label class="label-text">Your Credits</label>
                <div class="balance-display" id="credits">1000</div>
            </div>
            
            <div class="button-group">
                <button class="btn btn-primary btn-block" id="startButton">🎮 START GAME 🎮</button>
                <button class="btn btn-success btn-block" id="cashoutButton" disabled>💰 CASH OUT 💰</button>
            </div>
            
            <div class="alert alert-info mt-lg">
                <p><strong>Strategy:</strong> Cash out early for safe wins, or risk it for huge multipliers!</p>
            </div>
        </div>
    </div>
</div>

<style>
.game-content {
    text-align: center;
}

.egg-grid {
    display: grid;
    grid-template-columns: repeat(5, 1fr);
    gap: var(--spacing-md);
    max-width: 500px;
    margin: var(--spacing-xl) auto;
    padding: var(--spacing-lg);
    background: rgba(255, 255, 255, 0.05);
    border-radius: var(--radius-lg);
    border: 2px solid var(--accent-gold);
}

.egg {
    aspect-ratio: 1;
    background: linear-gradient(135deg, #FFD700, #FFA500);
    border-radius: 50%;
    border: 3px solid var(--accent-gold);
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 32px;
    cursor: pointer;
    transition: all 0.3s ease;
    box-shadow: 0 4px 10px rgba(255, 215, 0, 0.3);
}

.egg:hover:not(.revealed) {
    transform: scale(1.1);
    box-shadow: 0 6px 20px rgba(255, 215, 0, 0.5);
}

.egg.revealed {
    cursor: not-allowed;
    transform: scale(0.95);
}

.egg.gem {
    background: linear-gradient(135deg, #10b981, #059669);
    border-color: #10b981;
}

.egg.bone {
    background: linear-gradient(135deg, #ef4444, #dc2626);
    border-color: #ef4444;
}

.game-stats {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
    gap: var(--spacing-md);
    padding: var(--spacing-lg);
    background: rgba(255, 255, 255, 0.05);
    border-radius: var(--radius-lg);
}

.stat-box {
    display: flex;
    flex-direction: column;
    padding: var(--spacing-md);
    background: rgba(0, 0, 0, 0.3);
    border-radius: var(--radius-md);
}

.stat-label {
    font-size: var(--font-size-sm);
    opacity: 0.7;
    margin-bottom: var(--spacing-sm);
}

.stat-value {
    font-size: var(--font-size-xl);
    font-weight: var(--font-weight-bold);
}

.form-select {
    width: 100%;
    padding: var(--spacing-md);
    background: rgba(255, 255, 255, 0.05);
    border: 1px solid var(--border-light);
    border-radius: var(--radius-md);
    color: var(--text-primary);
    font-size: var(--font-size-md);
    cursor: pointer;
}

.form-select:focus {
    outline: none;
    border-color: var(--accent-gold);
}

.quick-bet-buttons {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: var(--spacing-sm);
}

@media (max-width: 768px) {
    .egg-grid {
        grid-template-columns: repeat(4, 1fr);
        max-width: 100%;
    }
    
    .egg {
        font-size: 24px;
    }
}
</style>

<?php include '../includes/footer.php'; ?>
