<?php
/**
 * GameSense Fantasy - Mines Game
 * Click tiles to reveal gems, avoid mines!
 */

require_once '../config/config.php';

$page_title = "Mines Game";
$page_description = "Click tiles to reveal gems and avoid mines in this thrilling game!";
$page_css = "game.css";
$page_js = "mines.js";

include '../includes/header.php';
?>

<div class="game-container">
    <div class="game-wrapper">
        <!-- Game Area -->
        <div class="game-area">
            <h2 class="game-title">💣 MINES GAME 💎</h2>
            
            <div class="game-content">
                <!-- Mines Grid -->
                <div id="minesGrid" class="mines-grid">
                    <!-- Grid will be generated by JavaScript -->
                </div>
                
                <!-- Game Stats -->
                <div class="game-stats mt-lg">
                    <div class="stat-box">
                        <span class="stat-label">Current Multiplier:</span>
                        <span class="stat-value text-gold" id="currentMultiplier">1.00x</span>
                    </div>
                    <div class="stat-box">
                        <span class="stat-label">Tiles Revealed:</span>
                        <span class="stat-value text-gold" id="tilesRevealed">0/25</span>
                    </div>
                    <div class="stat-box">
                        <span class="stat-label">Potential Win:</span>
                        <span class="stat-value text-success" id="potentialWin">0</span>
                    </div>
                </div>
                
                <!-- How to Play -->
                <div class="game-instructions mt-lg p-md card">
                    <h3 class="text-gold mb-md">📖 How to Play</h3>
                    <ul>
                        <li>💰 Place your bet and select number of mines</li>
                        <li>🎮 Click "START GAME" to begin</li>
                        <li>🔲 Click tiles to reveal gems</li>
                        <li>💎 Each gem increases your multiplier</li>
                        <li>💣 Hit a mine = Game Over (lose bet)</li>
                        <li>💵 Click "CASH OUT" anytime to collect winnings</li>
                        <li>⚠️ More mines = higher risk = bigger multipliers!</li>
                    </ul>
                </div>
            </div>
        </div>
        
        <!-- Control Panel -->
        <div class="control-panel">
            <h2 class="control-title">Game Controls</h2>
            
            <div class="control-section mb-xl">
                <label class="label-text">Bet Amount</label>
                <div class="input-group">
                    <input type="number" id="betAmount" value="10" min="1" max="500">
                    <span class="input-suffix">Coins</span>
                </div>
                <div class="quick-bet-buttons mt-md">
                    <button class="btn btn-sm btn-secondary quick-bet" data-amount="10">10</button>
                    <button class="btn btn-sm btn-secondary quick-bet" data-amount="50">50</button>
                    <button class="btn btn-sm btn-secondary quick-bet" data-amount="100">100</button>
                    <button class="btn btn-sm btn-secondary quick-bet" data-amount="max">MAX</button>
                </div>
            </div>
            
            <div class="control-section mb-xl">
                <label class="label-text">Number of Mines</label>
                <select id="mineCount" class="form-select">
                    <option value="3">3 Mines (Easy)</option>
                    <option value="5" selected>5 Mines (Medium)</option>
                    <option value="10">10 Mines (Hard)</option>
                    <option value="15">15 Mines (Extreme)</option>
                </select>
            </div>
            
            <div class="control-section mb-xl">
                <label class="label-text">Your Credits</label>
                <div class="balance-display" id="credits">1000</div>
            </div>
            
            <div class="button-group">
                <button class="btn btn-primary btn-block" id="startButton">🎮 START GAME 🎮</button>
                <button class="btn btn-success btn-block" id="cashoutButton" disabled>💰 CASH OUT 💰</button>
            </div>
            
            <div class="alert alert-info mt-lg">
                <p><strong>Strategy:</strong> More mines = bigger multipliers, but higher risk!</p>
            </div>
        </div>
    </div>
</div>

<style>
.game-content {
    text-align: center;
}

.mines-grid {
    display: grid;
    grid-template-columns: repeat(5, 1fr);
    gap: var(--spacing-sm);
    max-width: 500px;
    margin: var(--spacing-xl) auto;
    padding: var(--spacing-lg);
    background: rgba(255, 255, 255, 0.05);
    border-radius: var(--radius-lg);
    border: 2px solid var(--accent-gold);
}

.tile {
    aspect-ratio: 1;
    background: linear-gradient(135deg, rgba(124, 58, 237, 0.5), rgba(255, 215, 0, 0.2));
    border-radius: var(--radius-md);
    border: 2px solid var(--accent-gold);
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 28px;
    cursor: pointer;
    transition: all 0.3s ease;
    box-shadow: 0 4px 10px rgba(124, 58, 237, 0.3);
}

.tile:hover:not(.revealed) {
    transform: scale(1.05);
    box-shadow: 0 6px 20px rgba(255, 215, 0, 0.4);
    background: linear-gradient(135deg, rgba(124, 58, 237, 0.7), rgba(255, 215, 0, 0.3));
}

.tile.revealed {
    cursor: not-allowed;
    transform: scale(0.95);
}

.tile.gem {
    background: linear-gradient(135deg, #10b981, #059669);
    border-color: #10b981;
}

.tile.mine {
    background: linear-gradient(135deg, #ef4444, #dc2626);
    border-color: #ef4444;
}

.game-stats {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
    gap: var(--spacing-md);
    padding: var(--spacing-lg);
    background: rgba(255, 255, 255, 0.05);
    border-radius: var(--radius-lg);
}

.stat-box {
    display: flex;
    flex-direction: column;
    padding: var(--spacing-md);
    background: rgba(0, 0, 0, 0.3);
    border-radius: var(--radius-md);
}

.stat-label {
    font-size: var(--font-size-sm);
    opacity: 0.7;
    margin-bottom: var(--spacing-sm);
}

.stat-value {
    font-size: var(--font-size-xl);
    font-weight: var(--font-weight-bold);
}

.form-select {
    width: 100%;
    padding: var(--spacing-md);
    background: rgba(255, 255, 255, 0.05);
    border: 1px solid var(--border-light);
    border-radius: var(--radius-md);
    color: var(--text-primary);
    font-size: var(--font-size-md);
    cursor: pointer;
}

.form-select:focus {
    outline: none;
    border-color: var(--accent-gold);
}

.quick-bet-buttons {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: var(--spacing-sm);
}

@media (max-width: 768px) {
    .mines-grid {
        max-width: 100%;
    }
    
    .tile {
        font-size: 20px;
    }
}
</style>

<?php include '../includes/footer.php'; ?>
